apiVersion: constraints.gatekeeper.sh/v1beta1
kind: IngressMustUseWaf
metadata:
  name: ingressmustusewaf-constraint
spec:
  match:
    kinds:
      - apiGroups: ["extensions", "networking.k8s.io"]
        kinds: ["Ingress"]