apiVersion: apps/v1
kind: Deployment
metadata:
  name: cic-vpx
spec:
  selector:
    matchLabels:
      app: cic-vpx
  replicas: 1
  template:
    metadata:
      name: cic-vpx
      labels:
        app: cic-vpx
      annotations:
    spec: 
      serviceAccountName: vpx-ingress-k8s-role
      containers:
      - name: cic-vpx
        image: "quay.io/citrix/citrix-k8s-ingress-controller:1.26.7"
        env:
         # Set NetScaler NSIP/SNIP, SNIP in case of HA (mgmt has to be enabled) 
         - name: "NS_IP"
           value: "x.x.x.x"
         - name: "NS_PROTOCOL"
           value: "HTTPS"
         - name: "NS_PORT"
           value: "443" 
         - name: "NS_VIP"
           value: "x.x.x.x"
         # Set username for Nitro
         - name: "NS_USER"
           valueFrom:
            secretKeyRef:
             name: nsvpxlogin
             key: username
         # Set user password for Nitro
         - name: "NS_PASSWORD"
           valueFrom:
            secretKeyRef:
             name: nsvpxlogin
             key: password
         # Set log level
         - name: "EULA"
           value: "yes"
         - name: "NS_APPS_NAME_PREFIX"
           value: "oc"
         - name: "ROUTE_LABELS"
           value: "name in (hotdrink,colddrink,guestbook)"
        args:
          - --ingress-classes
            vpx
          - --feature-node-watch
            true
        imagePullPolicy: Always
---
