apiVersion: citrix.com/v1
kind: waf
metadata:
    name: wafurlchecks
spec:
#    ingressClassName: vpx // required when you want to create waf policy only for this workload. If you have more than one CIC configuring same ADC then without ingressClass, waf policy will be created for all workloads
    servicenames:
        - frontend-colddrinks
    application_type: 
        - HTML
# change html error page server details as per your setup
    html_error_object: "http://10.217.14.99/crd/error_page.html"
    target:
        path:
            - /
    security_checks:
        common:
          allow_url: "on"
          block_url: "on"
    relaxations:
        common:
          allow_url:
            urls:
                - payment.php
                - cover.php
    enforcements:
        common:
          block_url:
            urls:
                - "^[^?]*(passwd|passwords?)([.][^/?]*)?([?].*)?$"
                - "^[^?]*(htaccess|access_log)([.][^/?]*)?([~])?([?].*)?$"