apiVersion: citrix.com/v1
kind: waf
metadata:
    name: wafhtmlxsssql
spec:
#    ingressClassName: vpx // required when you want to create waf policy only for this workload. If you have more than one CIC configuring same ADC then without ingressClass, waf policy will be created for all workloads
    servicenames:
        - frontend-hotdrinks
# change html error page url as per your setup
    html_error_object: "http://10.217.14.99/crd/error_page.html"
    security_checks:
        html:
          cross_site_scripting: "on"
          sql_injection: "on"