apiVersion: citrix.com/v1beta1
kind: ratelimit
metadata:
  name: ratelimit
spec:
  servicenames:
    - front-end-headless
  selector_keys:
   basic:
    per_client_ip: true
  req_threshold: 2
  timeslice: 60000
  throttle_action: "RESPOND"