apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: citrix
spec:
  controller: citrix.com/ingress-controller
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-vpx-monitoring
  annotations:
#   ingress.citrix.com/insecure-termination: "allow"
   ingress.citrix.com/frontend-ip: "10.105.158.195"
   ingress.citrix.com/insecure-port: "8080"
spec:
  ingressClassName: citrix
  rules:
  - host:  grafana.beverages.com
    http:
      paths:
      - path: 
        backend:
          serviceName: grafana
          servicePort: 3000
  - host:  prometheus.beverages.com
    http:
      paths:
      - path: 
        backend:
          serviceName: prometheus-server
          servicePort: 9090
  - host:  kibana.beverages.com
    http:
      paths:
      - path:
        backend:
          serviceName: kibana
          servicePort: 5601
  - host:  elasticsearch.beverages.com
    http:
      paths:
      - path:
        backend:
          serviceName: elasticsearch
          servicePort: 9200
