apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
spec:
  selector:
    matchLabels:
      app: echoserver
  replicas: 1
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - image: ealen/echo-server:latest
        imagePullPolicy: IfNotPresent
        name: echoserver
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: pet-service
spec:
  ports:
  - port: 7030
    targetPort: 80
  selector:
    app: echoserver
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  ports:
  - port: 7040
    targetPort: 80
  selector:
    app: echoserver
---
apiVersion: v1
kind: Service
metadata:
  name: play-service
spec:
  ports:
  - port: 7050
    targetPort: 80
  selector:
    app: echoserver
