apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: citrix
spec:
  controller: citrix.com/ingress-controller

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hotdrinks-ingress
spec:
  ingressClassName: citrix  
  rules:
  - host:  hotdrink.beverages.com
    http:
      paths:
      - path: 
        backend:
          serviceName: frontend-hotdrinks
          servicePort: 80
  - host:  tea
    http:
      paths:
      - path: 
        backend:
          serviceName: tea-beverage
          servicePort: 80
  - host:  coffee
    http:
      paths:
      - path: 
        backend:
          serviceName: coffee-beverage
          servicePort: 80
